server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: core-service
  main:
    allow-circular-references: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/cloud_oj}?allowMultiQueries=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${DB_POOL_SIZE:10}
      max-lifetime: 30000
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${SERVICE_HOST:${spring.cloud.client.ip-address}}:${SERVICE_PORT:${server.port}}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml