#!/bin/bash
set -e
build_dir="cmake-build-release"

if [ -d ${build_dir} ]; then
  rm -rf ${build_dir}
fi

mkdir ${build_dir}

cmake -B ${build_dir} \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_SYSTEM_PROCESSOR=x86_64 \
  -DCMAKE_C_FLAGS=-m64 \
  -DCMAKE_CXX_FLAGS=-m64 \
  -G "Unix Makefiles"

if [ "$1" == "install" ]; then
  sudo cmake --build ${build_dir} --target all install
  sudo rm -r ${build_dir}
else
  cmake --build ${build_dir} --target all
fi
