#!/bin/bash
set -e
# clean && exit
if [ "$1" == "clean" ]; then
  cd services && mvn clean && cd ..
  if [ -d "target" ]; then
    rm -rf target
  fi
  if [ -d "judge/cmake-build-debug" ]; then
    rm -rf judge/cmake-build-debug
  fi
  if [ -d "judge/cmake-build-release" ]; then
    rm -rf judge/cmake-build-release
  fi
  if [ -d "web/dist" ]; then
    rm -rf web/dist
  fi
  exit 0
fi

echo "build start."
cd judge
./build
cd ../web
npm install
npm run build
cd ../services
mvn clean -B package '-Dmaven.test.skip=true'
cd ..
# build images
if [ "$1" == "docker-image" ]; then
  mkdir services/judge-service/target/bin
  cp judge/cmake-build-release/{judge,judged} services/judge-service/target/bin/
  docker build -t cloudoj-web web
  docker build -t cloudoj-registry services/registry
  docker build -t cloudoj-gateway services/gateway
  docker build -t cloudoj-storage services/file-service
  docker build -t cloudoj-core services/core-service
  docker build -t cloudoj-judge services/judge-service
  exit 0
fi

# archive artifacts
if [ -d "target" ]; then
  rm -rf target/*
fi
mkdir -p target/web
mkdir -p target/bin
mkdir -p target/services/lib
mv web/dist/* target/web/
mv services/gateway/target/*.jar target/services/gateway.jar
mv services/registry/target/*.jar target/services/registry.jar
mv services/file-service/target/*.jar target/services/file-service.jar
mv services/core-service/target/*.jar target/services/core-service.jar
mv services/judge-service/target/*.jar target/services/judge-service.jar
# copy dependencies
mv -n \
  services/gateway/target/lib/* \
  services/registry/target/lib/* \
  services/file-service/target/lib/* \
  services/core-service/target/lib/* \
  services/judge-service/target/lib/* \
  target/services/lib/
cp judge/cmake-build-release/{judge,judged} target/bin/
cp .deploy/conf/*.conf target/
# create setup script
# shellcheck disable=SC2035
cd target && tar --owner=0 --group=0 --mode=755 -cvf cloud-oj-linux64.tar.gz *
touch setup
tee setup <<EOF >/dev/null
#!/bin/bash
set -e
sudo useradd judge || true
sudo mkdir -p /opt/cloud-oj
sudo mkdir -p /var/lib/cloud-oj
sudo chown judge /var/lib/cloud-oj
sudo tar -xvf cloud-oj-linux64.tar.gz -C /opt/cloud-oj/
sudo ln -sf /opt/cloud-oj/bin/judge /usr/bin/judge
sudo ln -sf /opt/cloud-oj/bin/judged /usr/bin/judged
EOF
cd ..
echo "build complete."
