const ApiPath = {
  LOGIN: "/api/auth/login",
  LOGOFF: "/api/auth/logoff",
  REFRESH_TOKEN: "/api/auth/refresh_token",
  VERIFY: "/api/auth/verify",
  IMAGE: "/api/core/file/img",
  AVATAR: "/api/core/file/img/avatar",
  TEST_DATA: "/api/core/file/data",
  PROBLEM_IMAGE: "/api/core/file/img/problem",
  PROBLEM_ADMIN: "/api/core/problem/admin",
  PROBLEM: "/api/core/problem",
  USER: "/api/core/user",
  USER_ADMIN: "/api/core/user/admin",
  CONTEST: "/api/core/contest",
  CONTEST_INVITATION: "/api/core/contest/invitation",
  CONTEST_ADMIN: "/api/core/contest/admin",
  CONTEST_GEN_KEY: "/api/core/contest/admin/gen_key",
  CONTEST_PROBLEM: "/api/core/contest/problem",
  CONTEST_RANKING: "/api/core/ranking/contest",
  CONTEST_RANKING_ADMIN: "/api/core/ranking/admin/contest",
  CONTEST_SCORE_DETAIL: "/api/core/ranking/admin/contest/detail",
  RANKING: "/api/core/ranking",
  SOLUTION: "/api/core/solution",
  SUBMIT: "/api/judge/submit",
  ADMIN_SUBMIT: "/api/judge/submit",
  QUEUE_INFO: "/api/judge/admin/queue_info",
  PROFILE: "/api/core/user/profile",
  OVERVIEW: "/api/core/user/overview",
  SETTINGS: "/api/core/settings"
}

export default ApiPath
