#!/bin/bash
set -e
function has_command() {
  which "$1" &>/dev/null
}

if has_command apt-get; then
  curl -sL https://deb.nodesource.com/setup_lts.x | sudo bash -
  sudo apt-get update
  sudo apt-get install -y \
    gcc \
    g++ \
    cmake \
    libboost-iostreams-dev \
    libboost-program-options-dev \
    maven \
    openjdk-17-jdk-headless \
    nodejs
elif has_command dnf; then
  sudo dnf install -y \
    gcc \
    g++ \
    cmake \
    boost-devel \
    maven \
    java-17-openjdk-devel \
    nodejs
fi
