#!/bin/bash
set -e
NAME1=mysql_cloudoj
NAME2=rabbitmq_cloudoj

if docker ps -a | grep $NAME1 >/dev/null; then
  docker start $NAME1
else
  docker run --name $NAME1 \
    -p 3306:3306 \
    -e "MYSQL_ROOT_PASSWORD=root" \
    -e "MYSQL_ROOT_HOST=%" \
    -v "$PWD"/sql:/docker-entrypoint-initdb.d \
    -v mysql-cloudoj:/var/lib/mysql \
    -d mysql:8.0
fi

if docker ps -a | grep $NAME2 >/dev/null; then
  docker start $NAME2
else
  docker run --name $NAME2 \
    -p 5672:5672 \
    -p 15672:15672 \
    -e "RABBITMQ_DEFAULT_USER=admin" \
    -e "RABBITMQ_DEFAULT_PASS=admin" \
    -v rabbitmq-cloudoj:/var/lib/rabbitmq/mnesia \
    -d rabbitmq:3.11-management-alpine
fi
