server:
  port: 8080

spring:
  application:
    name: gateway
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/cloud_oj?serverTimezone=Asia/Shanghai}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${DB_POOL_SIZE:10}
      max-lifetime: 30000
  jackson:
    default-property-inclusion: non_null
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core
          uri: lb://core-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/core/**
        - id: judge
          uri: lb://judge-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/judgement/**
        - id: file
          uri: lb://file-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/file/**
        - id: auth
          uri: lb://gateway
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/auth/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

mybatis:
  configuration:
    map-underscore-to-camel-case: on
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${SERVICE_HOST:${spring.cloud.client.ip-address}}:${SERVICE_PORT:${server.port}}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/

logging:
  file:
    name: /var/log/api-gateway.log
  level:
    root: warn

project:
  token-valid-time: ${TOKEN_VALID_TIME:4}