server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_oj?serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
      max-lifetime: 30000
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://core-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/core/**
        - id: judge
          uri: lb://judge-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/judgement/**
        - id: file
          uri: lb://file-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/file/**
        - id: auth
          uri: lb://gateway
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/auth/**
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
app:
  token-valid-time: 4