server:
  port: 8761

spring:
  application:
    name: registry
  boot:
    admin:
      context-path: /admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  environment: prod
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: /app/log/register-center.log
  level:
    root: warn