server:
  port: 8761
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT:2000}
    max-threads: ${TOMCAT_MAX_THREADS:800}

spring:
  application:
    name: registry

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  environment: prod
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: /app/log/register-center.log
  level:
    root: warn
    group._204: info