version: '3.7'

services:
  mysql:
    container_name: cloud_oj_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d"

  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: cloud_oj_rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=cloud@oj
      - RABBITMQ_DEFAULT_PASS=cloud@oj
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq:/var/lib/rabbitmq/mnesia"

volumes:
  mysql-data:
  rabbitmq: