version: '3.4'

services:
  oj-mysql:
    container_name: oj-mysql
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "oj-mysql-data:/var/lib/mysql"
      - "./config:/etc/mysql/conf.d"
      - "./init:/docker-entrypoint-initdb.d"

  oj-rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: oj-rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=cloud@oj
      - RABBITMQ_DEFAULT_PASS=cloud@oj
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "oj-rabbitmq:/var/lib/rabbitmq/mnesia"

volumes:
  oj-mysql-data:
  oj-rabbitmq: