spring:
  profiles:
    active: dev
  application:
    name: judge-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    healthcheck:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: on
    default-enum-type-handler: group._204.oj.judge.type.ValueEnumTypeHandler
  mapper-locations: classpath:mybatis/mapper/*.xml