server:
  port: 8002
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT:200}
    max-threads: ${TOMCAT_MAX_THREADS:200}

spring:
  application:
    name: judge-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/cloud_oj?allowMultiQueries=true&serverTimezone=Asia/Shanghai}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${DB_POOL_SIZE:16}
      max-lifetime: 30000
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: ${RABBIT_URL:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:cloud@oj}
    password: ${RABBIT_PASSWORD:cloud@oj}
    listener:
      simple:
        acknowledge-mode: manual

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: on
    default-enum-type-handler: group._204.oj.judge.type.ValueEnumTypeHandler
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file:
    name: /app/log/judge-service.log
  level:
    root: warn
    group._204: info

project:
  file-dir: /var/lib/cloud_oj/
  code-dir: /tmp/code/
  runner-image: ${RUNNER_IMAGE:registry.cn-hangzhou.aliyuncs.com/cloud_oj/judge-runner:latest}
  core-pool-size: ${CORE_POOL_SIZE:8}
  max-pool-size: ${MAX_POOL_SIZE:8}
  queue-capacity: ${QUEUE_CAPACITY:8}