server:
  port: 8000

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${SERVICE_HOST:${spring.cloud.client.ip-address}}:${SERVICE_PORT:${server.port}}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/

logging:
  file:
    name: /var/log/file-server.log
  level:
    root: warn

project:
  file-dir: /var/lib/cloud_oj/
