server:
  port: 8000

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

project:
  file-dir: /mnt/e/cloud_oj/