server:
  port: 8000
  tomcat:
    accept-count: ${TOMCAT_ACCEPT_COUNT:200}
    max-threads: ${TOMCAT_MAX_THREADS:200}

spring:
  application:
    name: file-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:127.0.0.1:8761}/eureka/

logging:
  file:
    name: /app/log/file-server.log
  level:
    root: warn

project:
  file-dir: /var/lib/cloud_oj/
